# Generated by Django 4.0.1 on 2022-07-20 14:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
