# Generated by Django 4.0.1 on 2022-08-03 04:42

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_body', models.TextField()),
                ('video_video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
    ]
