# Generated by Django 4.0.1 on 2022-08-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_videoplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPlayer',
        ),
    ]
